### ISSUE TITLE
add anton to GBIF-Europe (organization)

### ISSUE THREAD

**Issue by ymgan** [GBIF-Europe/Regional-ECA-meetings#11]
The [Teams](https://github.com/orgs/GBIF-Europe/teams) are not visible to non-members. Is it possible to add @Antonarctica to the GBIF-Europe organization please? Thanks a lot!!

**Comment by dagendresen** [comment]
@ymgan  Invitation to @Antonarctica to join the GBIF Europe organisation is sent :-) Thanks!
