### ISSUE TITLE
ECA 2024 regional meeting in Zagreb, Croatia

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#12]
# ECA 2024 meeting

Dates: 27 and 28 May 2024 (_to be confirmed when the meeting budget is approved by the GBIF Secretariat_)
Location: hosted by GBIF Croatia in Zagreb (meeting budget to be approved by the GBIF Secretariat)

# Other events in the same time-period, dates to avoid
* Biodiversa+ Metaplantcode kick-off 13-15 May 2024
* World Biodiversity Day (in Netherlands) 22 May 2024
* ---- `GBIF ECA, Monday 27 May and Tuesday 28/5 2024, in Zagreb` ----
* DiSSCo GA6, Friday 31 May 2024
* Biodiversa+ online data management workshop 6-7 June 2024
* BioDT annual meeting, 11-12 June 2024
* European Congress of Conservation Biology is Bologna 17-21 June 2024 https://eccb2024.eu/

## Bank holidays in Croatia, dates to avoid:
* 30 May
* 17 June
* 20 June
* 25 June

**Comment by dagendresen** [comment]
Maybe explore a venue in Eastern Europe, maybe in the Balkans?

**Comment by dagendresen** [comment]
The ECA 2024 regional meeting was discussed at the [ECA breakout at the GB30 Global NODES in Canberra](https://github.com/GBIF-Europe/Regional-ECA-meetings/issues/24)

> Regional ECA meeting 2024
> Possible venue(s): 
> Balkan, maybe Bulgaria - Pensoft is positive in providing support to organisation
> Oleg is planning a baltic meeting anyway
> Want to encourage the organisation of the region that do not yet have well established GBIF nodes
> Concern that Bulgaria is still further than other balkan countries. (e.g. no direct flight)
> We have support from regional support staffs to help with the organisation
> Romania is not a member but they are interested to join
> Once we have the date and places, we can have a list of contacts
> Need a different dynamics for discussions to attract new members - e.g. showcase of node involvement in larger projects
> Business meetings align back to back with the regional ECA meeting 
> 3 groups: Outreach, Infrastructure, academic curriculum
> Setting the dates: (May?) Second half of May, maybe last week of May or in June 
> Continue on [GitHub issue #12](https://github.com/GBIF-Europe/Regional-ECA-meetings/issues/12)

**Comment by dagendresen** [comment]
Contact with the GBIF node in Croatia about hosting the next regional ECA meeting in Croatia.
Need to confirm and find dates.
Dag will prepare a poll for dates.

**Comment by dagendresen** [comment]
At GB30 we agreed to find a week in late May or early June for the ECA 2024

Week 20, Mon 13 May to Fri 17 May
Week 21, Mon 20 May to Fri 24 May
Week 22, Mon 27 May to Fri 31 May
Week 23, Mon 3 June to Fri 7 June
Week 24, Mon 10 June to Fri 14 June
Week 25, Mon 17 June to Fri 21 June

Please indicate (below) if any of these weeks are conflicting with other events!

**Comment by wkmor1** [comment]
European Congress of Conservation Biology is Bologna 17-21 June https://eccb2024.eu/
Week 24 for our regional meeting would be good for anyone going to both. Zagreb and Bologna are a relatively short and direct bus ride apart.

**Comment by vajohansson** [comment]
Parts of week 23 and 25 are national holidays in Sweden so I would be happy if we could avoid these weeks. Otherwise it works anytime. Week 22 would be best.

**Comment by nielsraes** [comment]
Week 22 - week 25 ok for me
22 May (week 21) - World Biodiversity Day where NLBIF organizes some activities

**Comment by mnhn-paul** [comment]
just be aware that May 30 is a [national holiday in Croatia](https://www.timeanddate.com/holidays/croatia/statehood-day).

otherwise I have currently no restrictions in dates.

**Comment by MichelleJudge** [comment]
I have other commitments on week 22 so won't be able to attend if it falls on the week.
Otherwise I have no restrictions currently.

**Comment by ymgan** [comment]
week 21 (21-23 May) TaxonWorks together (https://together.taxonworks.org/), but GBIF ECA would be our priority

**Comment by DimEvil** [comment]
Week 20, Mon 13 May to Fri 17 May 👍  👍 
Week 21, Mon 20 May to Fri 24 May 👎 
Week 22, Mon 27 May to Fri 31 May 👍 
Week 23, Mon 3 June to Fri 7 June 👎 
Week 24, Mon 10 June to Fri 14 June 👍 🥇 
Week 25, Mon 17 June to Fri 21 June (ECCB2024) 👎 

How many days would the meeting be? I prefer starting on Monday

**Comment by dagendresen** [comment]
Looks like week 24 (June 10-14) is the best week for most ECA nodes. We plan to suggest the ECA 2024 meeting on Monday 10/6 and Tuesday 11/6 plus a social event either before or after.

We also explore a possible regional training event on Wednesday 12/6 (need funding).

We also explore if the Biodiversa+ Metaplancode kick-off will be back-to-back after the ECA 2024, maybe Thursday 13/6 and Friday 14/6.

Suggest to discuss and try to decide at the next ECA Zoom on Monday 29th January (at 13:00 CET).

**Comment by DimEvil** [comment]
3-6 june is not a good time....

**Comment by dagendresen** [comment]
Hi @DimEvil - why is 3-6 June not a good time?

**Comment by DimEvil** [comment]
Because I can't be there most probably!

Op ma 29 jan. 2024 19:21 schreef Dag Endresen ***@***.***>:

**Comment by lkatusic** [comment]
> just be aware that May 30 is a [national holiday in Croatia](https://www.timeanddate.com/holidays/croatia/statehood-day).
> 
> otherwise I have currently no restrictions in dates.

Hi!

Holidays in Croatia are 30.5., 22.6. and 25.6., but 25.6. is a working day.  

Luka

**Comment by dagendresen** [comment]
Would week 22, Monday 27/5 and Tuesday 28/5. And a regional workshop on 29/5 work ok - with the holiday on Thursday 30/5? (Was a bad week for Ireland though).

**Comment by mnhn-paul** [comment]
> Would week 22, Monday 27/5 and Tuesday 28/5. And a regional workshop on 29/5 work ok - with the holiday on Thursday 30/5? (Was a bad week for Ireland though).

would work for me

**Comment by MichelleJudge** [comment]
> Would week 22, Monday 27/5 and Tuesday 28/5. And a regional workshop on 29/5 work ok - with the holiday on Thursday 30/5? (Was a bad week for Ireland though).

Depending on flights, I could potentially attend the Monday and Tuesday. If that works best for everyone then happy to go with those dates.

**Comment by wouteraddink** [comment]
31 May will be DiSSCo GA meeting, with 30 May needed for travel

**Comment by dagendresen** [comment]
Please reserve the dates Monday 27 May and Tuesday 28 May 2024 for the regional GBIF ECA meeting. 
We will let you know when the meeting budget is approved by the GBIF Secretariat.

(Note that the DiSSCo GA6 is on Friday 31 May)

**Comment by mnhn-paul** [comment]
maybe @dagendresen you can close this issue due to the meeting being behind us?
