### ISSUE TITLE
GB30 attendance from GBIF ECA nodes

### ISSUE THREAD

**Issue by ymgan** [GBIF-Europe/Regional-ECA-meetings#18]
https://gb30.gbif.org/

Some are choosing QT Canberra, see more hotels at https://gb30.gbif.org/travel-accommodation#hotels

It is advised to book the hotel earlier as there is another conference taking place around the area at the same time.

**Comment by dagendresen** [comment]
I have booked QT Canberra 15 to 20 Oct (Dag, Norway)
