### ISSUE TITLE
2022 ECA regional meeting (timing & venue)

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#2]
# Planning for the ECA 2022 regional meeting

2022 is a year without a global nodes meeting, and thus regional nodes meetings in all regions

Venue: [Neimenster](https://www.neimenster.lu/evenementiel/) -- [Musée national d'histoire naturelle Luxembourg](https://www.mnhn.lu/), [Luxemburg](https://www.google.com/maps/place/Luxembourg+National+Museum+of+Natural+History/@49.6096406,6.1334819,16.98z/data=!4m13!1m7!3m6!1s0x479545b9ca212147:0x64db60f602d392ef!2sLuxembourg!3b1!8m2!3d49.815273!4d6.129583!3m4!1s0x0:0x6c7278cdcf180a29!8m2!3d49.6098421!4d6.1357047)
Dates: [23-25 May 2022](https://www.gbif.org/event/96c29d-9c11-476f-a011-3148ed9/europe-and-central-asia-nodes-meeting-2022)#GBIFECA2022

ECA 2022 meeting program discussed here https://github.com/GBIF-Europe/Regional-ECA-meetings/issues/1

## In-person _versus_ Digital _versus_ Hybrid
* Is an in-person meeting possible? Do we want a hybrid meeting?
* [ECA 2020](https://drive.google.com/drive/u/0/folders/1_LFPvw9i20Por3iJXETnpWWQJsQX6yoa) & the [ECA 2021](https://drive.google.com/drive/u/0/folders/1ABaRzoYjGfWyZiXWDJMR5L0FgE7RBTVB) session at the GNM2021 were both digital (because of COVID)
* **Decision: in person meeting**

## Meeting venue?
  * [ECA 2020](https://drive.google.com/drive/u/0/folders/1_LFPvw9i20Por3iJXETnpWWQJsQX6yoa) was originally scheduled to be hosted by GBIF Luxembourg --> but was COVID-postponed --> and moved to a virtual digital event
  * [ECA 2021](https://drive.google.com/drive/u/0/folders/1ABaRzoYjGfWyZiXWDJMR5L0FgE7RBTVB) was organized as a side-event at the virtual digital Global Nodes Meeting
  * **ECA 2022** in Luxembourg ... ??
_I agree that it would be great if Luxembourg could host us this year. (Piotr)_
+1 --> plan A (Dag)
  * Poland has expressed interest in hosting one of the regional meetings - 2022?
_Poland is not yet ready, but probably it will be possible next year. In June we will submit a work program for the Polish GBIF Node for next 5 years, which would include hosting meetings, so we could cover some costs. (Piotr)_
  * Other nodes?
  *  * GBIF Netherlands might be able to provide a plan B venue for ECA 2022
 * **Decision: Venue** [Neimenster](https://www.neimenster.lu/evenementiel/) -- [Musée national d'histoire naturelle Luxembourg](https://www.mnhn.lu/), [Luxemburg](https://www.google.com/maps/place/Luxembourg+National+Museum+of+Natural+History/@49.6096406,6.1334819,16.98z/data=!4m13!1m7!3m6!1s0x479545b9ca212147:0x64db60f602d392ef!2sLuxembourg!3b1!8m2!3d49.815273!4d6.129583!3m4!1s0x0:0x6c7278cdcf180a29!8m2!3d49.6098421!4d6.1357047)

## Venue back-to-back with another event - building bridges?
  * SPNCH 2022 in Edinburgh 5-10 June, https://spnhc2022.com/ --> consult w [UK Node](https://www.gbif.org/country/GB/participation)...?
  * International Conference on DNA Barcoding and Biodiversity (ICDBB) will take place in Sofia, Bulgaria, from 25th to 27th of May 2022, https://cmebg.com/en/sabitia/icdbb2022/ --> [no Bulgaria Node yet](https://www.gbif.org/country/BG/summary)
  * Coordinate and align with [OBIS](https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6)/[EurOBIS](http://www.eurobis.org/) ...?

## Budget?
 * Total budget for the 2022 regional Nodes meetings is 32k€ (GBIF core budget)
 * Budget split per region, and thus for the ECA region to be decided (in February)
 * Other sources of funding?
 * Estimate of costs?
   * Any costs for venue, lunches, hosted dinner? (Covered by hosting node?)
   * Any need to cover travel costs for ECA nodes?
   * Any possibility to cover travel costs to invite observers from non-member countries?
   * ...?

## GBIFS Guidelines
 * [GBIFS guidelines for hosting regional GBIF nodes meetings](https://gbif.box.com/s/0y8l7wkmix8xdr8kssatm6iy9gue4ryl)

**Comment by ptyk** [comment]
I added comments in the body. Is it a good way? Otherwise they would not be clearly visible, treated as this note - purely technically.

**Comment by dagendresen** [comment]
I have contacted Tania to ask about interest in hosting in Luxembourg in 2022...
We could plan a Zoom session among ECA nodes to discuss the ECA meeting together...?

**Comment by dagendresen** [comment]
Draft Doodle pool
https://doodle.com/poll/su2yspqbd7pnaaix?utm_source=poll&utm_medium=link (multi-day range)
https://doodle.com/poll/9ecx5mgvs65cuhzu?utm_source=poll&utm_medium=link (text)

**Comment by dagendresen** [comment]
Note that the meeting venue (Cultural Center next to the museum in Luxembourg) is now (for the month of May) only vacant 23-25 May!

Note also that we kind of hope to have the date more or less fixed before the Nodes Steering Group meeting tomorrow (24 Feb).

**Comment by dagendresen** [comment]
The [registration is now open](https://nettskjema.no/a/263050) for the Europe and Central Asia (ECA) regional GBIF Nodes meeting, on 23-25 May in Luxembourg. All ECA Nodes are asked to register also if they are NOT able to attend.
Please register early to support our planning! You can modify your registration later!
Registration form: [https://nettskjema.no/a/263050](https://nettskjema.no/a/263050 )
Meeting program: https://bit.ly/gbif-eca2022 
Venue locations: https://bit.ly/gbif-eca2022map  (including hotel recommendations)

**Comment by dagendresen** [comment]
Dear all,
Many thanks for your registration for the [GBIF ECA meeting in Luxembourg next week](https://bit.ly/gbif-eca2022)! To help us to plan for and book the lunches and the hosted dinner, please answer this survey form before Wednesday 18th May this week.

https://nettskjema.no/a/269559 

Please prepare for the meeting by watching the [pre-recorded videos from the GBIF Secretariat](https://vimeo.com/showcase/9515918).
[GBIF event page](https://www.gbif.org/event/96c29d-9c11-476f-a011-3148ed9/). Meeting program at https://bit.ly/gbif-eca2022
