### ISSUE TITLE
GB30 ECA breakout session, 2023-10-17

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#24]
# Global Nodes Meeting Regional Breakout Session, 2023-10-17

>As part of the global nodes meeting on 17 October in Canberra, we will have a 1.5-hour session dedicated to regional breakout discussions. The regional representatives are expected to set the agenda and chair these sessions. We would recommend you nominate someone from within the group to take notes from the discussions so these can be shared with all nodes afterward. As possible agenda items, we would like to suggest that you discuss plans for a regional nodes meeting in 2024, outreach activities to strengthen participation in ECA, and collaborative projects ideas, including for CESP, but I expect that you will have lots of items to pick up on.

>Agenda https://docs.google.com/document/d/1dvhGZCruHLtnLwi3pnFfiXtYRudsv4XbhE27-xKZXlY

**Comment by ymgan** [comment]
I can help with note taking if needed :D

**Comment by nielsraes** [comment]
1. Where will we organize the next ECA meeting? With the regional ECA support team (Salza and Oleg) now formally established and to support their mission to attract new GBIF partners from eastern Europe we consider organizing the next ECA meeting (spring 2024) in the region. Suggestions for suitable localities are welcome.

**Comment by ymgan** [comment]
Not sure if it makes sense to discuss this in the ECA breakout session, but I am curious (and interested) in the possibility of having a shared European AI infrastructure for biodiversity applications e.g. [SYM05 AI Contributions to biodiversity data & data standardisation: Opportunities and challenges](https://www.tdwg.org/conferences/2023/session-list/#sym05)
