### ISSUE TITLE
ECSA2024 in Vienna 3-6 April 2024

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#29]
GBIF has two available personal discount codes for the upcoming [ECSA2024](https://2024.ecsa.ngo/) Conference in Vienna on 3-6 April 2024 and Kyle Copas is asking of two of us from ECA nodes would be planning to join the conference.

https://2024.ecsa.ngo/

For Early Bird registrations before 22 January 2024, this makes a registration €350 instead of €410, and for regular registrations up to 15 March, €400 instead of €460.

**Comment by mnhn-paul** [comment]
@dagendresen  I think you can close this issue

**Comment by dagendresen** [comment]
Thanks! - feel also anybody from us free to close issues you identify as completed
