### ISSUE TITLE
SPNCH-TDWG 2024

### ISSUE THREAD

**Issue by ymgan** [GBIF-Europe/Regional-ECA-meetings#31]
Is anyone attending [SPNCH-TDWG 2024](https://www.tdwg.org/conferences/2024/)? 

Registration is open: https://register.oxfordabstracts.com/event/6771?preview=false

Accommodation: https://www.oki-conven.jp/en/neighborhoodaccommodations/

Has anyone booked the accommodation?

**Comment by vajohansson** [comment]
Hi,
I have registered, but not booked any accommodation. Maybe we can have a chat about this next week at the ECA meeting?

/Veronika


Veronika A. Johansson, PhD

Node Manager, GBIF Sweden
+46 (0)851954036 | +46(0)708306021

#citethedoi


[Logo for Swedish Museum of Natural History]

From: Yi-Ming Gan ***@***.***>
Sent: den 21 maj 2024 08:42
To: GBIF-Europe/Regional-ECA-meetings ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GBIF-Europe/Regional-ECA-meetings] SPNCH-TDWG 2024 (Issue #31)


Is anyone attending SPNCH-TDWG 2024<https://url11.mailanyone.net/scanner?m=1s9JCY-0004EQ-5v&d=4%7Cmail%2F90%2F1716273600%2F1s9JCY-0004EQ-5v%7Cin11d%7C57e1b682%7C12918722%7C9499237%7C664C424E889C345D45C30B27B8A14820&o=%2Fphtw%3A%2Fwtsodw.gg.rtwen%2Fccernof%2F4202%2Fse&s=QNbzqZzGpvDfS6rPYIfa-z--DIU>?

Registration is open: https://register.oxfordabstracts.com/event/6771?preview=false<https://url11.mailanyone.net/scanner?m=1s9JCY-0004EQ-5v&d=4%7Cmail%2F90%2F1716273600%2F1s9JCY-0004EQ-5v%7Cin11d%7C57e1b682%7C12918722%7C9499237%7C664C424E889C345D45C30B27B8A14820&o=%2Fphte%3A%2Frtsotgifr.xseraorcstadbectsem%2Fv.o%3F6ntr71p%2F7aeevs%3Dfliwe&s=-4YJFmu15KxRgg1cj8qQ9I3PieY>

Accommodation: https://www.oki-conven.jp/en/neighborhoodaccommodations/<https://url11.mailanyone.net/scanner?m=1s9JCY-0004EQ-5v&d=4%7Cmail%2F90%2F1716273600%2F1s9JCY-0004EQ-5v%7Cin11d%7C57e1b682%7C12918722%7C9499237%7C664C424E889C345D45C30B27B8A14820&o=%2Fphtw%3A%2Fwtsokw.v-cnoinjenn%2Fe%2F.phheioorogbocdaammdco%2Fsnoit&s=WACXag2-s4ixb4cQ_PAfStjEvxM>

Has anyone booked the accommodation?
