### ISSUE TITLE
GB31 Port - anyone going?

### ISSUE THREAD

**Issue by mnhn-paul** [GBIF-Europe/Regional-ECA-meetings#33]
I'll be replacing Luxembourg usual head of delegation for the upcoming GB31 in/near Porto.

Was wondering if anyone else is going as I'm starting to plan my trip, I'll arrive on 27th of September (for a personal weekend in Porto)  and leave on the 5th.

**Comment by wouteraddink** [comment]
I will probably not go.

**Comment by andrejjh** [comment]
Hi Paul,

I will be attending 31st Governing Board and staying at Villa Boutique C
Hotel, arrival on September 30.
See you soon

André Heughebaert <https://andrejjh.github.io/>

**Comment by dagendresen** [comment]
I am also arriving on the 27th for a personal weekend in Porto/Vila do Conde.

**Comment by mnhn-paul** [comment]
great to hear that some of you are also going. I have also just booked B&B Hotels Vila do Conde

**Comment by ymgan** [comment]
none of us from SCAR could make it 😭 hope to see some of you in TDWG!
