### ISSUE TITLE
Monthly virtual ECA nodes sessions

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#4]
Invitation for informal monthly virtual sessions for [ECA nodes](https://www.gbif.org/the-gbif-network/europe) on the last Monday of each month.

- [Monday 2023-06-26](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=6&day=26&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- [Monday 2023-05-30](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=5&day=30&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST) _Whit Monday, a red day, school holiday (date moved down one day to Tuesday 30th May)_
- [Monday 2023-04-24](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=4&day=24&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- ~~[Monday 2023-03-27](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=3&day=27&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST) overlaps with GBIF mid-term meetings~~ (canceled)
- [Monday 2023-02-27](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2023&month=2&day=27&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (09:00 CET)

See also:
https://github.com/GBIF-Europe/RegionalWorkProgramme/issues
https://github.com/GBIF-Europe/Regional-ECA-meetings/issues

Zoom link on request, and in circulated calendar invitation.

Completely volunteer and informal opportunity to meet and work together on ECA nodes topics for 30-60 minutes depending on interest. Primarily for [GBIF ECA participant node managers](https://www.gbif.org/the-gbif-network/europe), however, node staff, and representatives of GBIF observers are also most welcome to join the virtual sessions.

![eurasia-time-zone-map](https://user-images.githubusercontent.com/4330242/159457513-bca045db-e6cc-40c6-a7d6-e2370fdd4d1f.jpg)

Dates in 2022:

- [Monday 2022-11-28](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=11&day=28&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (09:00 CET)
- [Monday 2022-10-31](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=10&day=31&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (09:00 CET, winter-time)
- [Monday 2022-09-26](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=9&day=26&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST, the week before GB29)
- [Monday 2022-08-29](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=8&day=29&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- [Monday 2022-07-25 ](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=7&day=25&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- [Monday 2022-06-27](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=6&day=27&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- ~~[Monday 2022-05-23](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=5&day=23&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST, the same day as the ECA 2022 starts)~~
- [Monday 2022-05-16](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=5&day=16&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST, moved one week up because of overlap with the on-site ECA 2022 in Luxembourg)
- [Monday 2022-04-25](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=4&day=25&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST)
- [Monday 2022-03-28](https://www.timeanddate.com/worldclock/meetingdetails.html?year=2022&month=3&day=28&hour=8&min=0&sec=0&p1=133&p2=16&p3=195&p4=69&p5=37&p6=101&p7=367&p8=370&p9=244&p10=385) (10:00 CEST, summer-time)

**Comment by ptyk** [comment]
Is there a way to have the meeting plan as a calendar file or a link to import it as a whole? I am using Google Calendar.

**Comment by dagendresen** [comment]
I plan to prepare complete calendar invitations when we agree to go ahead with the virtual meeting plan (and maybe agree on the dates?). The idea is anyhow for the meetings to be very informal so that ECA nodes can drop in or not spontaneously with no need to register in advance.

**Comment by ymgan** [comment]
@dagendresen is it possible to please re-add me to the calendar? I am not sure what I did, but I did not receive any calendar invitation this year so I thought there was no meeting until I saw this issue, sorry!

**Comment by dagendresen** [comment]
Out of the office this week, updated the calendar for Monday next week, and will add the remaining calendar invitations next week...

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by ErikKusch** [comment]
Following up with @ymgan's suggestion, here is a link to [a scheduling poll platform](https://www.when2meet.com/) which I use whenever I need to organise joint meetings

**Comment by samariddinbarotov** [comment]
Hello @dagendresen, I hope you are doing well. 
Today, the ECA node meeting is at 13 o'clock Dushanbe time if I don't make a mistake?

**Comment by dagendresen** [comment]
This information about our monthly online ECA meetings moved up to the front READ ME page at https://github.com/GBIF-Europe/Regional-ECA-meetings/blob/main/README.md

Closing this issue.
