### ISSUE TITLE
ECA 2023 regional meeting in Warsaw, Poland

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#5]
### Call for all ECA nodes to [suggest topics for the ECA 2023](https://docs.google.com/document/d/1__2TzzkmZJNVUUwuqcWk4FkEKRy7GlzUyICg4wB_FSc/edit)

Dates: 15-18 May 2023
Location: Warsaw, Poland
Short URL: https://bit.ly/gbif-eca2023

See also
[ECA 2023 Warsaw GDrive document](https://docs.google.com/document/d/1__2TzzkmZJNVUUwuqcWk4FkEKRy7GlzUyICg4wB_FSc/edit)
[ECA 2022 Luxembourg GDrive folder](https://drive.google.com/drive/folders/1iKF4_UTj2vR002vXPgnGv7kYGczWdruF)
[ECA 2021 session at GB28 Gdrive planning folder](https://drive.google.com/drive/folders/1ABaRzoYjGfWyZiXWDJMR5L0FgE7RBTVB?usp=sharing)
[ECA 2020 Online GDrive folder](https://drive.google.com/drive/folders/1_LFPvw9i20Por3iJXETnpWWQJsQX6yoa?usp=sharing)
[ECA 2019 Oslo GDrive folder](https://drive.google.com/drive/folders/1wC8-uIruBFoizCzAVNroUJ3FY4_d2aDl?usp=sharing)
...

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.

**Comment by dagendresen** [comment]
After we complete the meeting report we can close this issue
