### ISSUE TITLE
COST deadline 2023-10-25

### ISSUE THREAD

**Issue by dagendresen** [GBIF-Europe/Regional-ECA-meetings#8]
The GBIF nodes in Europe have previously prepared some [COST network](https://www.cost.eu/) proposals.

The next deadline for submitting a COST network [proposal is 2023-10-25](https://www.cost.eu/funding/open-call-a-simple-one-step-application-process/).

https://www.cost.eu/funding/open-call-a-simple-one-step-application-process/

Are any of us interested in leading a new COST proposal?

**Comment by mnhn-paul** [comment]
> [COST Inclusiveness Target Countries (ITC)](https://odin-cost.com/mobility/inclusiveness-target-countries-itc-conference-grants/) – Albania, Bosnia and Herzegovina, Bulgaria, Croatia, Cyprus, Czech Republic, Estonia, Hungary, Latvia, Lithuania, Luxembourg, Malta, Moldova, Montenegro, Poland, Portugal, Romania, Serbia, Slovakia, Slovenia, Turkey, and the Republic of North Macedonia.

@dagendresen there seems to be a more up to date version of the lsit [here](https://www.cost.eu/about/strategy/excellence-and-inclusiveness/): 
Albania, Armenia, Bosnia and Herzegovina, Bulgaria, Cyprus, Czech Republic, Estonia, Croatia, Georgia, Greece, Hungary, Lithuania, Latvia, Malta, Moldova, Montenegro, Poland, Portugal, Romania, Slovenia, Slovakia, Republic of North Macedonia, Republic of Serbia, Turkey and Ukraine
